#
# ██████╗ ██████╗ ██████╗         OPProtector 2023 (Operator Security System)
# ██╔═══██╗██╔══██╗██╔══██╗       Version: 1.0.1
# ██║   ██║██████╔╝██████╔╝       Contributors: Kasun Hapangama(ka0un)
# ██║   ██║██╔═══╝ ██╔═══╝        GitHub:https://github.com/ka0un/OPProtector
# ╚██████╔╝██║     ██║            Discord:https://dsc.gg/sundevs
# ╚═════╝ ╚═╝     ╚═╝             Website: https://ka0un.github.io/OPProtector/
#

#===============================================================================
# Password Settings
#===============================================================================

password-settings:
  enabled: true
  session-hours: 24
  use-gui: true
  interval-secounds: 20
  pas-command: "pas"
  encrypt-passwords: true

#===============================================================================
# Lockdown Settings
#===============================================================================

lockdown-settings:
  block-player-move: true
  block-break-blocks: true
  block-place-blocks: true
  block-player-commands: true
  block-item-drop: true
  block-item-pickup: true
  block-damage: true
  allow-flight: false
  commands-whitelist:
    - "/pas"
    - "/auth"
    - "/register"
    - "/login"
    - "/changepassword"
    - "/changepass"

#===============================================================================
# Scanner Settings
#===============================================================================

scanner-settings:
  scan-on-join: true
  scan-on-player-op-command: true
  scan-on-console-op-command: true
  scan-from-live-scanner: true
  scan-for-blacklisted-permissions: true
  scan-for-gamemode-creative: true
  check-for-bungeeguard: true
  blacklisted-permissions:
    - "essentials.*"
    - "*"
    - "bungeecord.command.*"
    - "minecraft.command.*"
    - "fawe.*"
    - "worledit.*"
    - "bukkit.*"
    - "minecraft.*"
    - "worldedit.*"
    - "worldguard.*"
    - "luckperms.*"
    - "lp.*"
    - "luckperms.*"
    - "luckperms.trusteditor"
    - "luckperms.editor"
    - "luckperms.user.permission.set"
    - "lands.admin.*"
    - "lands.bypass.*"
    - "excellentcrates.*"
    - "citizens.admin"
    - "minecraft.admin"
    - "plhide.bypass"

#===============================================================================
# Commands Settings
#===============================================================================

commands-settings:
  not-in-operators-list:
    - 'deop %player%'

  have-blacklisted-perms:
    - 'deop %player%'

  admin-ip-changed:

  failed-password-timeout:

#===============================================================================
# Discord Notifier Settings
#===============================================================================
discord-notifications:
  discord-webhook: ""
  notify-op-join: true
  notify-op-leave: true
  notify-auth-success : true
  notify-auth-failed: true
  notify-unauth-access: true




